---
abstract: 'transforms TeX and LaTeX into XML'
author:
  - 'Bruce Miller <bruce.miller@nist.gov>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LaTeXML
no_index:
  directory:
    - t
    - inc
requires:
  Archive::Zip: 0
  DB_File: 0
  File::Which: 0
  Getopt::Long: 2.37
  IO::String: 0
  Image::Size: 0
  JSON::XS: 0
  LWP: 0
  Parse::RecDescent: 0
  URI: 0
  XML::LibXML: 1.61
  XML::LibXSLT: 1.58
version: v0.7.999_03
